extends:
  - jason/react
  - 4catalyzer-typescript
globals:
  Promise: true
rules:
  prefer-const: off
  func-call-spacing: 'off'
  '@typescript-eslint/naming-convention': off
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/ban-ts-comment': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
